### ISSUE TITLE
Error when adding IP with octet such as '019' instead of 19

### ISSUE THREAD

**Issue by obikao** [netaddr/netaddr#197]
Title says it. 

100.019.255.255 causes the following error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from '100.019.255.255'`

Whereas 100.19.255.255 does not.

Python version 3.5.3 running version 0.7.19

**Comment by obikao** [comment]
I have solved the issue: 

use `flags=netaddr.ZEROFILL`

from: https://stackoverflow.com/questions/44852721/remove-leading-zeros-in-ip-address-using-python
