### ISSUE TITLE
Numerical representation in IP address not work

### ISSUE THREAD

**Issue by masterAllen** [netaddr/netaddr#234]
here is an example which is same as https://netaddr.readthedocs.io/en/latest/tutorial_01.html#numerical-representation, but i got errors in all statement :(
```
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from netaddr import *
>>> ip = IPNetwork('127.0.0.1')
>>> int(ip)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'IPNetwork'
>>> hex(ip)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'IPNetwork' object cannot be interpreted as an integer
>>> ip.bin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IPNetwork' object has no attribute 'bin'
>>> ip.bits()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IPNetwork' object has no attribute 'bits'
>>> ip.words
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'IPNetwork' object has no attribute 'words'
>>> 
```

**Comment by jstasiak** [comment]
Hey!

The example is about `IPAddress`, not `IPNetwork`. See:

```python
>>> from netaddr import IPAddress
>>> ip = IPAddress('192.0.2.1')
>>> int(ip)
3221225985
```

**Comment by masterAllen** [comment]
Yes! You saved me a lot of time，Thanks a lot!
